# Build on Push & Pull Request
name: Maven Build
on: 
  push:
    branches:
      ["release-4.9.0", "release-4.10.0", "release-5.0.0"]
  pull_request:
    branches:
      ["release-4.9.0", "release-4.10.0", "release-5.0.0"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
      
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build and analyze
        run: mvn clean install